### PR TITLE
Net 5 support and serializers exported to own projects

### LINKED ISSUE #25: Extract serialization concerns into independent projects
Good work guys,

In order to reduce dependencies, separate concerns and increase maintainability would you consider creating extra projects/packages for all serializers?

- Protobuf
- SystemTextJson
- MessagePack
- Avro
- Others

Also perhaps the serialization api would benefit from a different approach using ValueTask, Span and other structures.

Cheers.

### PR DESCRIPTION
**Pull request by RagingKore**
new: net 5 support
new: api refactored to support nullables
new: all serializers exported to specific projects
new: system text json serializer added as default
new: protobuf serializer now uses recyclable memory streams

closes #25 #26

### CODE REVIEW

**Comment by RagingKore** [comment]
Any feedback on this?

**Comment by sklivvz** [comment]
Looking!

**Comment by sklivvz** [comment]
There's a lot to unpack there! I think most changes are simply good. I have more... semantic doubts about nullables. What is the practical use case for storing nulls in a cache?

**Comment by sklivvz** [comment]
dupe of #30

**Pull request closed without merging**
